### ISSUE TITLE
Atomizer Roadmap

### ISSUE THREAD

**Issue by redonkulus** [acss-io/atomizer#452]
Hi everybody 👋! If you haven't noticed, there has been renewed activity in the project. Atomizer has served us well internally at Yahoo, as most properties have been using it to manage and build their CSS in production. While we have been using it for many years, we haven't been keeping the project as up to date as it could be.

Below is just some of the work that we plan to do to enhance the project.

### Welcome Carrie 🎉!

I would also like to welcome @carriemorrison as a core contributor to the project. She has been working at Yahoo for many years and is our de-facto CSS and Accessibility technical leader for many of our properties. She has extensive knowledge of ACSS/Atomizer and is very familiar with the architecture and concepts. Join me in welcoming her!

### Atomizer

- [ ] **Add new ACSS classes**: There has been an unprecedented amount of features and enhancements to the CSS spec since Atomizer was first released. We are currently evaluating the latest standards and adding missing classes to Atomizer. You can see the list in our [Google Sheet](https://docs.google.com/spreadsheets/d/1kp0_WaJ05n2QlFloOQXT1H6wNX2FmU-4/edit#gid=962252958). Feel free to comment or add suggestions.

### Website

- [x] Migrate website code from the `acss-io/acss-site` repository to the `acss-io/atomizer` repository.
- [x] Integrate Vercel in Pull Requests to automatically deploy the site for preview and testing.
- [ ] Review and update all content for accuracy (In progress)
- [ ] Re-organize navigation and content to make it easier to find information
- [ ] Add site search
- [ ] Add documentation pages for logical groupings of classes. Similar to the "Grid System" page which includes inline-block, flex and tables. 

### Project Updates

- [x] Migrate all active packages and website into the recently converted `atomizer` monorepo repository. This will make it easier to test new features and publish changes out together.
- [x] Integrate GitHub Dependabot to automatically update dependencies across libraries

This is just some of the work that is currently being scoped, we will update this issue in the future as we add new features and enhancements.

**Comment by roderickhsiao** [comment]
Some internal helpers we added at Tinder which not yet covered by the Google sheet

1. [image rendering](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering)
1. [backdrop filter](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter)
1. [font stretch](https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch)
1. [mix blend mode](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode)
1. [content-visibility](https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility)

**Comment by redonkulus** [comment]
Thanks @roderickhsiao I've added 1, 2, and 3 to the doc. 4 was already added. 5 doesn't seem to be implemented in Firefox or Safari yet, is it part of the spec yet or just a Google thing?

**Comment by roderickhsiao** [comment]
Thanks! 

For content visibility,
its currently module level 2 https://drafts.csswg.org/css-contain-2/#content-visibility

Safari (no singal) https://lists.webkit.org/pipermail/webkit-dev/2020-May/031217.html
Mozilla https://github.com/mozilla/standards-positions/issues/135

probably we can wait a bit

**Comment by redonkulus** [comment]
Good point. It's something Carrie and I have discussed. She added the [Alignment](https://acss.io/tutorials/alignment.html) page with examples and snippets to help. Is that what you had in mind?

I do like how Tailwind has a page per rule, which has examples, snippets, customizations. But adding a page per rule seems like a bit much to maintain. 

We were thinking of grouping like classes together on one page so that the examples are a little more real world like.

**Comment by roderickhsiao** [comment]
Yeah, I think the tutorial pages make sense!
Probably not a page per rule but some real-world UI like carousel/button ... etc to showcase that we can also build higher-level design systems using Atomizer will make people focus a bit more of how to use it instead of hating the syntax at first without giving a try lol

The examples on Tailwind of how to change font/theme are cool,
Perhaps adding a small example on those [syntax part](https://acss.io/guides/syntax.html) instead of full page snippets (we already have the snippet just not showing the UI).

I personally think Tailwind can get adopted pretty fast because their build-in class/theming make it very easy to start and the UI output is modern, lots of developers now start a project from boilerplate like create-react-app/nextjs and want to have a very easy way to begin with without designers.

**Comment by redonkulus** [comment]
> Perhaps adding a small example on those [syntax part](https://acss.io/guides/syntax.html) instead of full page snippets (we already have the snippet just not showing the UI).

Ya that's a good idea. Having the UI on the page with the examples is key to help users understand how it works.



> I personally think Tailwind can get adopted pretty fast because their build-in class/theming make it very easy to start and the UI output is modern, lots of developers now start a project from boilerplate like create-react-app/nextjs and want to have a very easy way to begin with without designers.

Ya I think that is where atomizer differs, Tailwind is more like Stencil (internal project), whereas Atomizer is more of a utility for building from scratch. I think its ok for atomizer to lean into the unopinionated side of its usage but with simple examples to show what is possible. Today, Tailwind charges for boilerplate templates that users can use, I think we can just provide those for free.

**Comment by jitendravyas** [comment]
+1 to PostCSS plugin

**Comment by redonkulus** [comment]
PostCSS plugin and many other integrations are documented on the Installation page https://acss.io/installation.html#bundler-integrations

**Comment by mikestopcontinues** [comment]
Now that there's a postcss plugin, should the Remix docs be updated to suggest it? Seems cleaner than a double-render, but perhaps there's something I'm missing.

**Comment by redonkulus** [comment]
@mikestopcontinues that's a good point. I haven't tested the PostCSS plugin with Remix yet, but worth a try. I created an issue to track it https://github.com/acss-io/atomizer/issues/646

If you have bandwidth, it would be helpful to test it out locally and see if there are any issues. Thanks!
